image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    command:
      ["--tls=false", "--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - format
  - build
  - docker-build-and-publish

before_script:
  - apk add --no-cache npm

format_code:
  stage: format
  script:
    - npm install --global prettier
    - prettier . --check

build_code:
  stage: build
  script:
    - npm install
    - npm run build

docker_build_and_publish:
  stage: docker-build-and-publish
  script:
    - docker build -t $DOCKER_USERNAME/vinventory_app:$CI_COMMIT_SHA .
    - docker tag $DOCKER_USERNAME/vinventory_app:$CI_COMMIT_SHA $DOCKER_USERNAME/vinventory_app:$CI_COMMIT_TAG
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/vinventory_app:$CI_COMMIT_SHA
    - docker push $DOCKER_USERNAME/vinventory_app:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
