apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vinventory.smtpConfigMapName" . }}
  labels:
    {{- include "vinventory.labels" . | nindent 4 }}
data:
  MINIO_ENDPOINT:  {{ .Values.env.minioEndpoint | quote }}
  MINIO_USE_SSL: {{ .Values.env.minioUseSsl | quote }}
  MINIO_BUCKET: {{ .Values.env.minioBucket | quote }}
