apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vinventory.postgresConfigMapName" . }}
  labels:
    {{- include "vinventory.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
