---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vinventory-secrets-database
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAC1ZOKlgFHJq9E0E0wSYC6Ht4BAUjtiq9ZEcGqAiIHxkgcTDOm9kmvGCXqwuuEbkIznxxpXxMhUCTZou7VDd3xIFek3FNq3g8nFenjPUI4auz4YZeOz1ilLEafUzqWqzihMwuQQ5E7mh+nEGRbXvS08+ovqdGeRZzKj8Lpz8ETinfhTunotmZvPzR2CDS4VfGEHXWTpjPZ3gAvqF2syznhw59z2IrWlyVQlHcBuzQLc8CBaW/BTXlY4pt+5bNZ6jEKWVaEQPE6KjzAG+rM2RXDr3uqxa2wqqA7OZXGLe9xZSPGK1xxociHGIjkwz/GuERhUIPViD9J2xGijcnS014DEN62mLj3Xdv55qiUNEoCm9sMFZR2CnMmvedl6lePY2uxlacFefrzzQjpkGQR2wy6EX/XKMAl1KRaxtsR/s0Ef1MjTnFxMsHzFhxZCmgwsgmWOdexiZMiD1ZlDYrarkaS3sXKHHNxWegxvkmONNwjUDFO44cHuqfc1c8Kl6ejDetkWE5qoTrl8wcZGNPvefzlEKQTk+c1fNnfeBtKqMIHPAppbwP6AjsSIrVVh7UVcKcNssPCD3ZekeUh22h6TQXbdP/YJhQUCsTj3Sj3S/2yFVaOETCxJhynVTXAUygflGc4sJ1EU/kj21Sc697y0dwVeLoZBV/NZEfN+W36qLYZW2mDnW2P+DLej3CQYV1kvYsV8gROCN4R0g==
  template:
    metadata:
      creationTimestamp: null
      name: vinventory-secrets-database
      namespace: default
    type: Opaque
