---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vinventory-secrets-minio
  namespace: default
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAXBRpE0jx9sdlcQTdmuO6T605JrqRFCCDCgm8j0ctLQf7zBcWQY3OuaBL0goqCGahrUR5RxN827sOFv+8NDLwxog9cO5/SIG/5V4KhegViniy4LUQb9TH2z7mqoq+T9O2yXxPTbmvABnroPyqofxhpRkwEBEIS8HfggAr2csPzw+TLyz/GuvL/hj8f4URMiS0lX6Vfo5fX1tg4Xdxhfk/nmFrMB0ZfXr2+R6YfQ+ilYvgbSGzz4DK/3rKe2QsZwjTkVE/c7FGekhgvNFYvPwujYUR8UzKYiRPBkeo1QL9vdJmz/LH7JyLtAukzhN0JGqWatNHLsUvdiKCXyQtnjxzhj/EX/VfAAB7A2ESsOF5BjQdmPyGP1AR3QvWJFtC/bqkCh8b9I78BOfRqsQiIdqx2bhbu3Ze1nGwEC9afGoZXFM8q3+Fiz1tLzq+6fJHNP+lg4ev2BiPEUXtFyCCvnkxtnJBR+oJ31BiWSIX+uWJXtRDatS1NDKmXNxaP60O5lJMfIzBPvr3ulpC+I8OCUra/BsuRPA90Klo8rsduu1b4d0KLD7hctocv1mPAhxHTiGtQNI4dNi2QR7LfXiQGTf79JOEBHSv7VDaL+pzEY3BIK0dDcpkbX9vBFqCh6EC9G4FEE5PuSHhH/UPI0ihkyX4hY4pIbx9pYNGw6BRZtUr6Yiel77oyVcyAi86G3ZozdtT9Muip68j6fYnNwly6fF1PyE4v/A==
    MINIO_SECRET_KEY: AgAX7bBK7mVWpFU4kykP6yxZfSbZL33iomN/NsrBRzHiAQtc5JauB3Z8ijFCb62mvrzy7cotSHblnIGcIOecAVPVumNk4WQ39FHMS1GsvUpzlNYnOLRIgL5PhY4ob03IYow8i2FqOVn5YnIwKUunfdL51C/JkKJgclh9OeBzMQIRzQQlGsMsc2yBz3XzUAzK3KZsUfn4b76Kur1x74F2UCZDst/P0QsVvKtPH5Q6JP1VEDwNxezYiMcnZBi3b/a+aDGmNLO6AieCqktPejOBb0RwefcvHrQgGV8gvoXwEmXSbxacRwc68psZAm00VlXMWfDNdgaYpXsxtxOPeXoPBqWgQS3Yq8ZQbZ39am5WKeb8vDEUU+yOiSFNZ7iLW6qH8B15EGnmzEWeDlviE78dGjzLZOovO4Xp97aGFW7Q6AFHs0rj60tUzYnlyDcYh6JB8aBPtJcmuDpSegBV+PKKCsr0vQICnGEFPQP2YCuDejbG/s03g6j3VTXtHQ8/Cui+6gnEUFYWR1UgVCt5eyGWHxNrX7zyuDZfKWzL0T0dc+GcKJXwPzhNhI6+PNdrLUc12rGUog4sEoHSvdgR/T1g27ouKrphTleO8sfBbe4IU8w+AgLX2Wi4UZAhsdXaSeD1NlRNhYwXMB/DIPlppeiSSLSQP94J1jGB23PwAZ6uNV5ZCLgyPF/Hf537WnpU7W9AI8ZZjUODB8/uz+OynOWXnzgxrxz7D1JpxWxHc+5FjQLMmCPzkS9fuObp
  template:
    metadata:
      creationTimestamp: null
      name: vinventory-secrets-minio
      namespace: default
    type: Opaque
