replicaCount: 2

image:
  repository: docker.io/odulsuzkisafilm/vinventory
  tag: 1.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true

env:
  # SMTP
  smtpHost: "smtp.gmail.com"
  smtpPort: "587"
  smtpUsername: "[yourSendingUsername]"
  senderEmail: "[yourSendingEmailAddress]"
  receiverEmail: "[yourReceiverEmailAddress]"

  # DB
  dbHost: "localhost"
  dbPort: "5432"
  dbUser: "[yourDbUser]"
  dbName: "[yourDbName]"

  # MINIO
  minioEndpoint: "192.168.128.164:9000"
  minioUseSsl: "false"
  minioBucket: "vinventory"

egress:
  enabled: true

cronjob:
  enabled: true
